In [1]:
import numpy as np

m_sqr_arrA = np.array([[1, 2], [4, -1]]) 
print(m_sqr_arrA)

m_sqr_arrB = np.array([[2, -3], [-4, 1]])
print(m_sqr_arrB)

m_sqr_arrR = m_sqr_arrA-m_sqr_arrB
print(m_sqr_arrR)


[[ 1  2]
 [ 4 -1]]
[[ 2 -3]
 [-4  1]]
[[-1  5]
 [ 8 -2]]


In [2]:
import numpy as np

m_sqr_arr = np.array ([[-1, 0, 2],[0, 1, 0],[1, 2, -1]])
m_sqr_arrR = m_sqr_arr * m_sqr_arr

print(m_sqr_arrR)


[[1 0 4]
 [0 1 0]
 [1 4 1]]


In [3]:
import numpy as np 

m_sqr_arrA = np.array ([[3,5],[6,-1]])
m_sqr_arrB = np.array ([[2,1],[-3,2]])
m_sqr_arrR = m_sqr_arrA.dot(m_sqr_arrB)
print(m_sqr_arrR)


[[-9 13]
 [15  4]]


In [4]:
m_sqr_arr = np.array ([[2,3,4],[1,0,6],[7,8,9]])
print(m_sqr_arr)
np.linalg.det(m_sqr_arr)


[[2 3 4]
 [1 0 6]
 [7 8 9]]


35.00000000000001

In [5]:
m_sqr_arr = np.array ([[1,2,3,4],[-2,1,-4,3],[3,-4,-1,2],[4,3,-2,-1]])
print(m_sqr_arr)
np.linalg.det(m_sqr_arr)


[[ 1  2  3  4]
 [-2  1 -4  3]
 [ 3 -4 -1  2]
 [ 4  3 -2 -1]]


900.0000000000009

In [6]:
m_sqr_arr = np.array([[1,2,-3],[0,1,2],[0,0,1]])
a_inv = np.linalg.inv(m_sqr_arr)
print(a_inv)


[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [7]:
a = np.array([[1,2,3,4],[3,-1,2,5],[1,2,3,4],[1,3,4,5]])
rank = np.linalg.matrix_rank(a)
print(rank)


2


In [8]:
#Матричний метод

A = np.array([[14,4,6],[5,-3,2],[10,-11,5]])
B = np.array([30,15,36])
print('A=', A)
print('B=',B)
A_inv = np.linalg.inv(A)
print(A_inv)
X = A_inv.dot(B)
print('X=',X)


A= [[ 14   4   6]
 [  5  -3   2]
 [ 10 -11   5]]
B= [30 15 36]
[[-0.09722222  1.19444444 -0.36111111]
 [ 0.06944444 -0.13888889 -0.02777778]
 [ 0.34722222 -2.69444444  0.86111111]]
X= [ 2. -1.  1.]


In [9]:
a = np.array([[14,4,6],[5,-3,2],[10,-11,5]])
print('A=',a)
b = np.array([30,15,36])
print('B=',b)

def kramer (a, b):
    a_det = np.linalg.det(A)
    print('Детермінант матриці = ', a_det)
    if (a_det != 0):
        print ('Розв*язуємо систему')
        
        x_m = np.array(a)
        x_m[:, 0] = b 
        print('x_m=', x_m)
        y_m = np.array(a)
        y_m[:, 1] = b 
        print('y_m=',y_m)

        z_m = np.array(a)
        z_m[:, 2] = b 
        print('z_m=',z_m)

        x = np.linalg.det(x_m) / a_det
        y = np.linalg.det(y_m) / a_det
        z = np.linalg.det(z_m) / a_det
        print('X = ', round(x,5))

        print('Y=', round(y,5))

        print('Z=', round(z,5))
    else:
        print('Розв*язків немає')
kramer(a,b)


A= [[ 14   4   6]
 [  5  -3   2]
 [ 10 -11   5]]
B= [30 15 36]
Детермінант матриці =  -72.0
Розв*язуємо систему
x_m= [[ 30   4   6]
 [ 15  -3   2]
 [ 36 -11   5]]
y_m= [[14 30  6]
 [ 5 15  2]
 [10 36  5]]
z_m= [[ 14   4  30]
 [  5  -3  15]
 [ 10 -11  36]]
X =  2.0
Y= -1.0
Z= 1.0


In [10]:
#2

import random 

n=int(input("N = "))
m=int(input("M = "))    
A = np.array([[random.randrange(0,10) for y in range(m)] for x in range(n)])

for x in range (m):
    for y in range (n):
        print (A[y][x], end=' ')
    print()
    
result = 0
sredne = 10
for x in range (m):
    for y in range (n):
        result = (A[y][x]) + result
    result = result / n
    if(result < sredne):
        sredne = result
print("Найменше середнє число з стовпців", sredne)



N = 4
M = 4
3 0 0 1 
4 5 8 4 
0 9 1 7 
9 9 2 9 
Найменше середнє число з стовпців 1.0
